### ISSUE TITLE
Error web verification

### ISSUE THREAD

**Issue by MatiasMinchaca** [AilynMS/ailyn-monitoring-system#1]
#### Environment
localhost

### Errors to solving
- When trying to create a web verification, the app returns the following error message:
"No available dkron agent"
![Screenshot from 2022-07-13 11-52-25](https://user-images.githubusercontent.com/85573304/178764266-a45a0118-2782-4029-abe6-dd0f711c5f0e.png)

But when we reload the page we see that it was created
![Screenshot from 2022-07-13 11-54-28](https://user-images.githubusercontent.com/85573304/178764720-f844fee8-1c4b-4184-bb48-794020b45577.png)

- Then when we want to change its state, it returns the same error as when creating it
![Screenshot from 2022-07-13 12-10-44](https://user-images.githubusercontent.com/85573304/178768763-87b2546a-b698-498b-97eb-adbbaba1eff1.png)

- To finish when we want to see your statistics, the app returns the following error message:
"Undefined index: results"
![Screenshot from 2022-07-13 12-15-31](https://user-images.githubusercontent.com/85573304/178769664-4c33d71e-e125-4bfe-9235-0ba641e873e6.png)

**Comment by eddymdz** [comment]
@MatiasMinchaca as you can see in the messsage: **No available dkron agent**, check what is happening dkron service

**Comment by eddymdz** [comment]
@MatiasMinchaca change in the Laravel environments the value of DKRON_URL for http://dkron:8080, this solves your problem
