### ISSUE TITLE
Error in user activation process

### ISSUE THREAD

**Issue by eddymdz** [AilynMS/ailyn-monitoring-system#3]
When I click over the link that the app send me to confirm my registration, I got an error 
![error_invalid_redirect](https://user-images.githubusercontent.com/31184671/180214398-fee55f25-a5b2-4943-aa57-c3524ce248f0.png)

**Comment by PabloBerrettoni** [comment]
@eddymdz This error can happen if the APP_URL in the backend has an invalid value. Does it have ' http://localhost:8080/ ' as value?

**Comment by eddymdz** [comment]
@PabloBerrettoni thanks, let me check

**Comment by eddymdz** [comment]
@PabloBerrettoni the problem was related with CLIENT_URL: https://github.com/AilynMS/ailyn-monitoring-system/commit/cb952489efe1e714dfdbeac342af9ea1b8863beb
