### ISSUE TITLE
Missing an .env.example in the frontend folder

### ISSUE THREAD

**Issue by MatiasMinchaca** [AilynMS/ailyn-monitoring-system#4]
- The readme.md in the frontend folder asks to copy the file ".env.example" and replace it with ".env"
But ".env.example" file does not exist in /frontend
![Screenshot from 2022-07-22 12-24-03](https://user-images.githubusercontent.com/85573304/180471883-1ba0b3ab-1752-431f-92bf-e33bd520a7bf.png)

**Comment by eddymdz** [comment]
@MatiasMinchaca done: https://github.com/AilynMS/ailyn-monitoring-system/commit/d205c78648b1b170a8b70edcb1896d4f96195b64
